M48
; DRILL file KiCad 10.0.4 date 2026-07-23T05:17:14
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-23T05:17:14+05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X27.75Y-99.355
X27.75Y-110.785
X311.0Y-65.57
X311.0Y-77.0
T2
X34.1Y-108.655
X304.65Y-67.7
T3
X29.5Y-40.5
X31.5Y-143.0
X309.5Y-40.5
X311.0Y-145.0
M30
